# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Todototum < Formula
  desc "See the whole TODO picture. Scan your codebase and generate reports"
  homepage "https://github.com/valerioTomassi/todototum"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/valerioTomassi/todototum/releases/download/v1.0.0/todototum_1.0.0_darwin_amd64.tar.gz"
      sha256 "3a30771c0d33706279057bfd340d58bb8da1eadf896f2239662fdb79dd34e430"

      def install
        bin.install "todototum"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/valerioTomassi/todototum/releases/download/v1.0.0/todototum_1.0.0_darwin_arm64.tar.gz"
      sha256 "038970d7c59b3e42ce1e7f7a493b62405d16b841bf68f2303655dbcdfe90c61f"

      def install
        bin.install "todototum"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/valerioTomassi/todototum/releases/download/v1.0.0/todototum_1.0.0_linux_amd64.tar.gz"
      sha256 "56a4a5084fb2369328a56a91740c3cc49fa53ad2e866b5a4201a84671babe60d"
      def install
        bin.install "todototum"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/valerioTomassi/todototum/releases/download/v1.0.0/todototum_1.0.0_linux_arm64.tar.gz"
      sha256 "6c0c01718aeeca6df9ee863f1de104877f0c1278171294496ad91e8b0136d185"
      def install
        bin.install "todototum"
      end
    end
  end

  test do
    system "#{bin}/todototum", "--version"
  end
end
