# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Todototum < Formula
  desc "See the whole TODO picture. Scan your codebase and generate reports"
  homepage "https://github.com/valerioTomassi/todototum"
  version "1.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/valerioTomassi/todototum/releases/download/v1.1.1/todototum_1.1.1_darwin_amd64.tar.gz"
      sha256 "d60390b86a4716f9422fc7f9d2b73031ca75fb8fb7b52d9fe41d792bfd58d741"

      def install
        bin.install "todototum"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/valerioTomassi/todototum/releases/download/v1.1.1/todototum_1.1.1_darwin_arm64.tar.gz"
      sha256 "21844439dc8ddf0d7f3b847f5eaa6e851a5c062dd9ccb64ceade6e4fa0bdd48d"

      def install
        bin.install "todototum"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/valerioTomassi/todototum/releases/download/v1.1.1/todototum_1.1.1_linux_amd64.tar.gz"
      sha256 "10eb2565bf6c8a028bc5293e71c4a4b49d30bc0847c2920d39fad9a76a907ecb"
      def install
        bin.install "todototum"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/valerioTomassi/todototum/releases/download/v1.1.1/todototum_1.1.1_linux_arm64.tar.gz"
      sha256 "1ee24aa496ec11a6fff9d44c1354cf962abb62c287de802216f1266b64cc8da4"
      def install
        bin.install "todototum"
      end
    end
  end

  test do
    system "#{bin}/todototum", "--version"
  end
end
