# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Todototum < Formula
  desc "See the whole TODO picture. Scan your codebase and generate reports"
  homepage "https://github.com/valerioTomassi/todototum"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/valerioTomassi/todototum/releases/download/v1.0.1/todototum_1.0.1_darwin_amd64.tar.gz"
      sha256 "b2ed49c23e25680ea0049547e2515437ada85ba3161293957f7df84ec4c80e39"

      def install
        bin.install "todototum"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/valerioTomassi/todototum/releases/download/v1.0.1/todototum_1.0.1_darwin_arm64.tar.gz"
      sha256 "48aed18d68e7d7f2db7994da5a38f164a828440e86bed4af6a33faf58c7ce64c"

      def install
        bin.install "todototum"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/valerioTomassi/todototum/releases/download/v1.0.1/todototum_1.0.1_linux_amd64.tar.gz"
      sha256 "3ed9e464b7a33498b32e8a411702313392a3c586d82509d221571cf25739f4d3"
      def install
        bin.install "todototum"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/valerioTomassi/todototum/releases/download/v1.0.1/todototum_1.0.1_linux_arm64.tar.gz"
      sha256 "0d07bf87cf61706e31c90b6bb631f3e49688ae7ca19ca411620dbd03bdfc197a"
      def install
        bin.install "todototum"
      end
    end
  end

  test do
    system "#{bin}/todototum", "--version"
  end
end
